### ISSUE TITLE
Custom Dataset Help!

### ISSUE THREAD

**Issue by Ce11an** [hugochan/K-Competitive-Autoencoder-for-Text-Analytics#33]
Hi,

I am trying to implement a custom data set with the KATE model, but I am unclear on a few things:

- I have created a BoW from my training data using Gensim but I am not sure what you mean by vocabulary?
- I am quite new to using GitHub in general, is there a way I can train the model within Jupyter Lab?
- If there is a more clear tutorial somewhere, could you point me in the right direction?

I would really appreciate your advice!

Kind regards,

Cellan.

**Comment by Ce11an** [comment]
By the way, does this only work on Python 2.7?

**Comment by hugochan** [comment]
> By the way, does this only work on Python 2.7?

It has not been tested under Python 3. But I think you should be able to easily adapt it to Python 3.

**Comment by hugochan** [comment]
> Hi,
> 
> I am trying to implement a custom data set with the KATE model, but I am unclear on a few things:
> 
> * I have created a BoW from my training data using Gensim but I am not sure what you mean by vocabulary?
> * I am quite new to using GitHub in general, is there a way I can train the model within Jupyter Lab?
> * If there is a more clear tutorial somewhere, could you point me in the right direction?
> 
> I would really appreciate your advice!
> 
> Kind regards,
> 
> Cellan.

Thank you for your interest to our work! For you questions:
1) The vocabulary is a set of word tokens that appear in your training data. You should be able to access it through Gensim.
2) I am not familiar with Jupyter Lab. But I think it is doable. You might want to check some references.
3) Unfortunately, there is no other tutorial regarding this repo.

Hope it helps.
